update to forms
onflow/flow pull request #198
Opened 2020-11-25 23:56 UTC by laynelafrance

2020-11-25 23:59 UTC, 10thfloor approved these changes

2020-11-25 23:59 UTC, 10thfloor commented on docs/content/token/delivery.mdx
> + 8. Now that you have your deposit address, you can begin the process to claim your FLOW from Dapper Labs
```suggestion
 8. Now that you have your deposit address, you can begin the process of claiming your FLOW from Dapper Labs
```

2020-11-26 00:00 UTC, 10thfloor commented on docs/content/token/delivery.mdx
> +Please submit your details to [this form](https://docs.google.com/forms/d/e/1FAIpQLSdJHHxA4IK6TGHId84YBh_zQ-DVPXLJ3_ektX9TdHiQPcC1LQ/viewform) if you are a FLOW backer.
```suggestion
Please submit your details using [this form](https://docs.google.com/forms/d/e/1FAIpQLSdJHHxA4IK6TGHId84YBh_zQ-DVPXLJ3_ektX9TdHiQPcC1LQ/viewform) if you are a FLOW backer. 
```

2020-11-26 00:00 UTC, 10thfloor requested changes
Nits.

2020-11-26 00:01 UTC, 10thfloor commented on docs/content/token/delivery.mdx
> +Please submit your detils to [this form](https://docs.google.com/forms/d/e/1FAIpQLSeeBuFVXoMmKwF141TD1jL_HTf3XN4-sTphPUYEB-Ed57vJLQ/viewform) if you are claiming a FLOW lease or grant.
```suggestion
Please submit your details using [this form](https://docs.google.com/forms/d/e/1FAIpQLSeeBuFVXoMmKwF141TD1jL_HTf3XN4-sTphPUYEB-Ed57vJLQ/viewform) if you are claiming a FLOW lease or grant.  
```

2020-11-27 05:51 UTC, psiemens approved these changes

2020-11-27 05:51 UTC, merged