Update index.md
onflow/flow pull request #230
Opened 2020-12-02 18:32 UTC by caseyturnerarrington

Cosmetic changes and added a FAQ section at the bottom.

Closes: #???

## Description

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2020-12-02 19:07 UTC, 10thfloor approved these changes

2020-12-02 19:09 UTC, 10thfloor approved these changes

2020-12-02 19:12 UTC, 10thfloor requested changes
@caseyturnerarrington 
There is still some weirdness.
Your best bet is to preview changes on the preview URL above ☝️ , not the github markdown editor :)

2020-12-07 19:23 UTC, caseyturnerarrington commented
Thanks @10thfloor ! I made a few more updates/changes. Can you please review?

2020-12-08 19:45 UTC, 10thfloor approved these changes

2020-12-08 19:55 UTC, merged