New rewards docs
onflow/flow pull request #237
Opened 2020-12-07 18:27 UTC by 10thfloor

Closes: #5037

2020-12-08 21:08 UTC, joshuahannan commented on docs/content/staking/rewards.mdx
> +## Rewards Calculation
Have you gotten confirmation from Layne or Roham that this info is allowed to be shared?

2020-12-08 21:09 UTC, joshuahannan commented
I think that the locked account setup document should remain the `token` section instead of the node operators section, because that document applies to everyone, not just node operators

2020-12-09 03:18 UTC, timmymmit requested changes
Added comments in file

2020-12-09 03:18 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +For more details you can read [this official post](https://www.onflow.org/post/flow-port-is-here) to familiarize yourself with the Flow Port app,
Use this link instead https://docs.onflow.org/support/flow-port/

2020-12-09 03:18 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +Coinlist will automatically re-stake any rewards you earn. If you'd like to withdraw or delegate stake to another node, you'll need to
Less is more here I think for custody providers. They wouldn't want us to point them away from their nodes. Lets just say if you would not like to have rewards re-staked automatically please contact support. Don't mention withdraw or delegate to another node.

2020-12-09 03:18 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +If you would like to delegate our locked FLOW to another node of your choosing, you'll need to contact Coinlist's support team.
Need to confirm if this is true with Brian. If not then lets just say its not possible to delegate using coinlist.

2020-12-09 03:18 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +If you would like to delegate your locked FLOW to another node of your choosing, you'll need to contact Kraken's support team.
Same comment as above

2020-12-09 03:18 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +
Say something like instructures will be provided as soon as they are ready and will be linked here.

2020-12-09 03:18 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +This section provides information for users who have acquired locked FLOW from the community sale, and are holding them in one of the following wallets.
or Custody providers.

2020-12-09 19:45 UTC, joshuahannan reviewed
Looks really good. I have a few suggestions and comments.

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/protocol/core-contracts/flow-id-table-staking.mdx
> +See the [staking events Documentation](../../staking/events) for more information about each event.
I tested this and the link took me to `protocol/core-contracts/flow-id-table-staking/events` when it should have taken me to `staking/events`. How do we link it correctly?

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/protocol/core-contracts/locked-tokens.mdx
> +See the [staking documentation](/protocol/core-contracts/flow-id-table-staking) for how to get info about a staked delegator.
```suggestion
See the [staking documentation](/protocol/core-contracts/flow-id-table-staking) for how to get info about a staked node.
```

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/staking/events.mdx
> +After this event the tokens will be a part of the delegator's `tokensUnstaking` balance.
```suggestion
After this event the tokens will be a part of the delegator's `tokensUnstaking` balance, where they are held for a whole epoch "unstaking period" with no rewards.
```

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/staking/events.mdx
> +After this event the tokens will be a part of the node operator's `tokensUnstaking` balance.
```suggestion
After this event the tokens will be a part of the node operator's `tokensUnstaking` balance, where they are held for a whole epoch "unstaking period" with no rewards.
```

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/staking/rewards.mdx
> +| Total Rewards % (Annual) | 5%             | 20%        | 5%           | 3%        |
```suggestion
| Total Rewards % (Annual) | 5%             | 20%        | 5%           | TBD      |
```

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/staking/rewards.mdx
> +| Total Rewards Amount     | 1,173,391 FLOW | ~4.4M FLOW | ~1.2M FLOW   |
```suggestion
| Total Rewards Amount     | 1,173,391 FLOW | ~4.4M FLOW | ~1.2M FLOW   | TBD
```

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/staking/rewards.mdx
> +Rewards will continue to accumulate in your account as long as you a re staked.
```suggestion
Rewards will continue to accumulate in your account as long as you are staked and operate your node properly.
```

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/staking/rewards.mdx
> +- TODO: Example of "General transaction for individuals to withdraw rewards and distribute to multiple accounts"
```suggestion
Nodes can use the **Withdraw Rewarded FLOW** ([TH.14](/protocol/core-contracts/locked-tokens/#token-holder)) transaction to withdraw their rewards back to their locked account.
Delegators can use the **Withdraw Rewarded FLOW** ([TH.24](/protocol/core-contracts/locked-tokens/#token-holder)) transaction to withdraw their rewards back to their locked account.

Then, any user can use the **Withdraw Unlocked FLOW** ([TH.01](/protocol/core-contracts/locked-tokens/#token-holder)) transaction to withdraw their rewards and unlocked FLOW from the locked account to the unlocked account.
```

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/staking/rewards.mdx
> +- Spend your FLOW in DApps on Flow! Take your newly liquid FLOW tokens to interact with DApps deployed on Flow Mainnet!
```suggestion
- Send your tokens to other Flow users with the **Transfer FLOW** ([FT.01](/protocol/core-contracts/flow-token/#transactions)) transaction.
- Spend your FLOW in DApps on Flow! Take your newly liquid FLOW tokens to interact with DApps deployed on Flow Mainnet!
```

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/support/flow-port/staking-guide.mdx
> +Within Flow Port, navigate to the ‘Stake & Delegate’ page to see details about your existing stake and/or delegate.
```suggestion
Within Flow Port, navigate to the ‘Stake & Delegate’ page to see details about your existing staked and/or delegated tokens.
```

2020-12-09 19:45 UTC, joshuahannan commented on docs/content/support/flow-port/staking-guide.mdx
> +This will also show you the rewards you have earned for your stake/delegate:
```suggestion
This will also show you the rewards you have earned for your staked/delegated tokens.
```

2020-12-09 23:46 UTC, joshuahannan commented on docs/content/protocol/core-contracts/flow-id-table-staking.mdx
> +See the [staking events Documentation](../../staking/events) for more information about each event.
```suggestion
See the [staking events Documentation](/staking/events) for more information about each event.
```

2020-12-10 01:05 UTC, githubwei commented on docs/content/staking/custody-providers.mdx
> +- **Stake owned nodes**: The provider will stake nodes they are running themselves
The provider will stake nodes they are running themselves -> The provider will delegate user tokens to nodes they are running themselves

2020-12-10 01:06 UTC, githubwei commented on docs/content/staking/custody-providers.mdx
> +- **Stake custom nodes**: The provider will stake nodes they choose, but may not own
The provider will stake nodes they choose, but may not own  -> The provider will delegate user tokens to nodes they choose, but may not own

2020-12-10 01:34 UTC, githubwei reviewed
Left some suggestions

2020-12-10 01:34 UTC, githubwei commented on docs/content/staking/rewards.mdx
> +  **Note:** If you would like to stake a different node than you're currently staking, you may need to contact you custody provider directly.
If you would like to stake a different node than the one you're currently staking, you may need to contact your custody provider directly

2020-12-10 01:34 UTC, githubwei commented on docs/content/staking/rewards.mdx
> +is available in the ecosystem to a wide variety of holders after the first few reward payments.
```suggestion
available in the ecosystem to empower a wide variety of use cases.
```

2020-12-10 01:34 UTC, githubwei commented on docs/content/staking/rewards.mdx
> +The rewards distribution schedule has been designed to ensure that enough liquid FLOW
```suggestion
The rewards distribution schedule has been designed to ensure there is enough liquid supply of FLOW
```

2020-12-10 01:34 UTC, githubwei commented on docs/content/staking/rewards.mdx
> +Using this model, any user will be able to easily aquire FLOW from many different places
```suggestion
```

2020-12-10 01:34 UTC, githubwei commented on docs/content/staking/rewards.mdx
> +in order to participate in the network.
```suggestion
```

2020-12-10 01:34 UTC, githubwei commented on docs/content/staking/rewards.mdx
> +The numbers in this table represent the total tokens that are paid as rewards each epoch.
```suggestion
The numbers in this table represent the total amount of tokens that are paid as staking rewards at each epoch to the entire Flow ecosystem participants.
```

2020-12-10 01:34 UTC, githubwei commented on docs/content/staking/rewards.mdx
> +Rewards are paid out at the end of each [epoch](/staking/#epochs) to all the users that have tokens staked.
```suggestion
Rewards are paid out at the end of each [epoch](/staking/#epochs) (approximately weekly) to all the users that have tokens staked.
```

2020-12-10 16:43 UTC, caseyturnerarrington commented
@10thfloor @timmymmit in the FAQ of the Flow Port guide, can you change the below sentence to include the link below in it?
'a.) Please see a list here (Coming soon!) for all node operators that you can delegate to. This list will be updated as new node operators are onboarded onto the network.'

Link to use for 'here': https://github.com/onflow/flow/blob/master/nodeoperators/NodeOperatorList.md

2020-12-10 17:14 UTC, timmymmit submitted a review, later dismissed

2020-12-10 17:14 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +If you would like to withdraw your rewards, you'll need to contact Coinlist's support team.
Remove If you would like to withdraw your rewards, you'll need to contact Coinlist's support team.
as it is already listed below.

2020-12-10 17:14 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +For details about how to delegate, or withdraw your rewards, you'll need to contact Kraken's support team by email.
Remove For details about how to delegate, or withdraw your rewards, you'll need to contact Kraken's support team by email. and put to the Withdrawing Rewards for Kraken.

2020-12-10 17:14 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +## Summary
Been asked by Layne to exclude this for now and keep as an internal reference for now.

2020-12-10 17:15 UTC, caseyturnerarrington commented on docs/content/support/flow-port/index.md
> +  - Withdraw/re-stake your earned rewards. If you decide to withdraw your rewards, this actions will happen instantly. If you decide to re-stake your rewards, the request will again sit in a pending
should be: this action* not actions

2020-12-10 17:25 UTC, timmymmit commented on docs/content/staking/custody-providers.mdx
> +## Summary
This being the Summary table below

2020-12-10 17:58 UTC, merged