adding more staking FAQs
onflow/flow pull request #249
Opened 2020-12-09 19:30 UTC by vishalchangrani

Adding some more staking related FAQs documented here: https://www.notion.so/dapperlabs/c2acf7e6b7a74edd8f72b5db09b58f52?v=3c979316e5cf4b8badd50a84baf7c0bb

## Description

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2020-12-09 19:49 UTC, joshuahannan approved these changes
Looks good! I have a few suggestions.

2020-12-09 19:49 UTC, joshuahannan commented on docs/content/staking/faq.mdx
> +### Is there a utility to generate the generate the FLOW addresses?
```suggestion
### Is there a utility to generate the FLOW addresses?
```

2020-12-09 19:49 UTC, joshuahannan commented on docs/content/staking/faq.mdx
> +The consensus node min 500K FLOW can be reached cumulatively with any combination of a lease and delegation. e.g. lease 250K and then delegate the remaining 250K.
```suggestion
The consensus node min 500K FLOW can be reached cumulatively with any combination of a lease and delegation as long as the lease is a minimum of 250k FLOW. e.g. lease 250K and then delegate the remaining 250K.
```

2020-12-09 19:49 UTC, joshuahannan commented on docs/content/staking/faq.mdx
> +The recipient of the leased tokens however has the ability to stake them for their nodes, but don't have the ability to withdraw them or do anything else with them.
```suggestion
The recipient of the leased tokens however has the ability to stake them for their nodes and withdraw the rewards from staking, but doesn't have the ability to withdraw them or do anything else with them.
```

2020-12-09 19:49 UTC, joshuahannan commented on docs/content/staking/faq.mdx
> +### How long will tokens be leased to us?
```suggestion
### How long are tokens leased?
```

2020-12-09 20:10 UTC, laynelafrance requested changes
committed changes

2020-12-09 21:32 UTC, 10thfloor approved these changes

2020-12-10 00:41 UTC, vishalchangrani commented
Closing this PR in favour or https://github.com/onflow/flow/pull/250 but retaining all the commits and changes.

2020-12-10 00:41 UTC, closed without merging