adding old access node data
onflow/flow pull request #422
Opened 2021-03-06 21:56 UTC by vishalchangrani

Closes: #???

## Description

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2021-03-08 17:50 UTC, laynelafrance requested changes
[here](/node-operation/spork/#mainnet) doesn't link out for me- it goes to a privileged page

2021-03-08 17:55 UTC, vishalchangrani commented
> [here](/node-operation/spork/#mainnet) doesn't link out for me- it goes to a privileged page

That link is relative and when the site is rendered it will work - you can checkout the preview of this change here -
https://flow-docs-git-vishal-acrhivalnodes-onflow.vercel.app/access-api#flow-access-node-endpoints

If you click `here` in the preview it will take you to right location.

2021-03-08 17:57 UTC, vishalchangrani commented on docs/content/access-api.md
> +##### We are still in the process of aggregating the past chain data but mainnet 5 to mainnet 1 spork data can be retrieved from the Access nodes mentioned [here](/node-operation/spork/#mainnet)
@laynelafrance the link here is relative...and we will not be sharing this github page but rather the docs site page https://docs.onflow.org/access-api which uses this md page.

2021-03-08 18:46 UTC, caseyturnerarrington approved these changes

2021-03-09 17:34 UTC, 10thfloor approved these changes

2021-03-09 17:34 UTC, merged