Update earn.mdx
onflow/flow pull request #61
Opened 2020-09-30 00:48 UTC by timmymmit

Updated links

Closes: #???

## Description

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2020-09-30 17:00 UTC, Kay-Zee requested changes
Links are not working here: https://flow-docs-git-timmymmit-patch-1.onflow.vercel.app/token/earn/

I think you need to remove the `#`

2020-09-30 17:00 UTC, Kay-Zee commented on docs/content/token/earn.mdx
> +- [Alpha Program](#https://www.onflow.org/flow-alpha)
```suggestion
- [Alpha Program](https://www.onflow.org/flow-alpha)
```

2020-09-30 17:00 UTC, Kay-Zee commented on docs/content/token/earn.mdx
> +- [Open World Builders](#https://medium.com/dapperlabs/open-world-builders-free-virtual-blockchain-bootcamp-cefe7f0ccb9f)
```suggestion
- [Open World Builders](https://medium.com/dapperlabs/open-world-builders-free-virtual-blockchain-bootcamp-cefe7f0ccb9f)
```

2020-09-30 19:22 UTC, Kay-Zee approved these changes

2020-11-03 02:43 UTC, psiemens approved these changes

2020-11-03 02:44 UTC, merged